### ISSUE TITLE
CSP frame-src blocked on Firefox for blob on Embedded app

### ISSUE THREAD

**Issue by bartcoppens** [Shopify/shopify-app-bridge#11]
## Describe the bug

Usage of the blog: protocol is denied on Firefox due to a Content-Security-Policy violation.

### To Reproduce

Create an embedded app. Add a datatable from https://datatables.net/.
Add an export button (https://datatables.net/reference/button/excelHtml5).
Use the export button on Firefox from the embedded app.
The export fails and the error on the console reads:
"Content Security Policy: The page’s settings blocked the loading of a resource at blob:https://app-v4.discountninja.io/547f6f2e-8f48-4068-80bb-350de3b7852e (“frame-src”)."

To reproduce the problem from a live app, install Discount Ninja on a development store (free) and access the reports. Click the Export buttons to trigger the issue. For more information see this video:
https://www.loom.com/share/2dfbc3abbe9e4a41bb77e454649704ba

### Expected behaviour

The browser should allow the visitor to download a csv or Excel file.
The expected behavior can be seen on a Chrome browser. 

### Packages and versions

- @shopify/app-bridge @ 1.27.2

## Platform

- OS: 10.0.19041.450
- Browser: I'm using FireFox 80.0.1 and Google Chrome 85.0.4183.83 on a Windows 10 machine.

**Comment by iainmcampbell** [comment]
I've done some investigation and consulted our security team. You should be able to use the [<a> download attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download) with a `blob:` URL to download a file without needing to navigate to it. I've verified that this works inside the embedded app iframe:

```js
var content = ['<a id="a"><b id="b">hey!</b></a>']
var blob = new Blob(content, {type : 'text/html'})
var blobURL = URL.createObjectURL(b)

var a = document.createElement('a')
a.innerText = 'hey'
a.setAttribute('href', blobURL)
a.setAttribute('download', 'hey.html')
document.appendChild(a)
```

**Comment by bartcoppens** [comment]
Hi Iain,

Looks like a good repro script indeed.
I tested it on Google: works. And on Firefox: fails.

Note, I had to tweak the script a bit to get it to work in my environment:
```
var content = ['<a id="a"><b id="b">hey!</b></a>']
var blob = new Blob(content, {type : 'text/html'})
var blobURL = URL.createObjectURL(blob)

var a = document.createElement('a')
a.innerText = 'hey'
a.setAttribute('href', blobURL)
a.setAttribute('download', 'hey.html')
document.getElementsByTagName('body')[0].appendChild(a)
```

**Comment by bartcoppens** [comment]
This video shows the repro of the issue in Firefox:
https://www.loom.com/share/34326a706ae84bbd87dad87f9f7a5e3c

**Comment by iainmcampbell** [comment]
hmm, it looks like Firefox interprets CSP differently than Chrome (and we thought the w3c specs were would fix this!). Based on your video and this Firefox bug report, it seems FF treats clicking on `<a download>` as navigating: https://bugzilla.mozilla.org/show_bug.cgi?id=1365502. The spec is a bit vague here: "the URLs which may be loaded into nested browsing contexts" (https://w3c.github.io/webappsec-csp/#directive-frame-src). I don't see any issues in the spec repo about this, either (https://github.com/w3c/webappsec-csp/issues), nor anything relevant in the chromium bug tracker (https://bugs.chromium.org/p/chromium/issues/list?q=frame-src%20data%20download&can=1).

I’ll look further into this; downloading a blob from within an embedded app is totally a reasonable thing to be able to do.

I also found this workaround from Shopify Community: https://community.shopify.com/c/Shopify-Apps/Refused-to-frame-http-xyz-com-because-it-violates-the-following/m-p/403701/highlight/true#M11625. Apparently creating another iframe inside your app’s iframe can get around CSP? I haven't tested this, and it seems counter to the purpose of CSP, but it might work.

**Comment by bartcoppens** [comment]
Hi @iainmcampbell, not sure if building iFrames in iFrames is my preferred solution. 
Do you have an update on this? Do you think it could be related to https://github.com/Shopify/shopify-app-bridge/issues/8?

**Comment by iainmcampbell** [comment]
That's fair, not my preferred solution either. I’m still looking into this.

**Comment by iainmcampbell** [comment]
Hi Bart, the security team has finished reviewing this and concluded that we are not able to change the content security policy. You’ll need to find a workaround for file downloads, sorry :(

**Comment by arberosmani** [comment]
> Apparently creating another iframe inside your app’s iframe can get around CSP? I haven't tested this, and it seems counter to the purpose of CSP, but it might work.

I tried this and it would work. I created a demo for this.

https://arberosmani.github.io/workaround-csp-frame-src-blocked-on-firefox/
