### ISSUE TITLE
app.getState('pos') - multiple devices returning identical pos.device.serialNumber 

### ISSUE THREAD

**Issue by derrickrc** [Shopify/shopify-app-bridge#136]
@samiulmonir06 

More context here: https://shopifypartners.slack.com/archives/CKK8FHFDF/p1656603899976759

This was first reported nearly 2 months ago and is affecting multiple merchants using our app - thank you.

**Comment by samiulmonir06** [comment]
@derrickrc : We have added a fix to resolve this issue. It should be available in `version 7.7.0`

**Comment by derrickrc** [comment]
@samiulmonir06 @heltisace I have additional information from merchants that this bug appears to be limited to newer iPads (e.g., 9th Generation). When you do your testing, please do so using 9th generation and other newer iPad models - thank you.

**Comment by heltisace** [comment]
@derrickrc got it, thanks! We tested the changes on the newer devices when pushing them, so hopefully everything will be okay. Let's wait until the next week to verify that the fix resolves the issue.

**Comment by heltisace** [comment]
Hey @derrickrc! We are rolling out POS 7.7.0 for iOS which should include the fix for this issue. If you cannot see the release, it should become available by the end of tomorrow. When you update to the new version let me know if the device id problem still persists. Thanks!

**Comment by derrickrc** [comment]
@heltisace thank you, but unfortunately this isn't fixed. Now there is a new bug - instead of returning an identical device.serialNumber for these devices, the device.serialNumber is changing on every unique session / app load instead of persisting for that device. 

Behavior on older iOS devices remains correct, the bug continues to affect newer iOS devices (tested this morning with a merchant using iPad Pro 10.5"). Their shop for reference is milk-pail-fresh-market.

**Comment by heltisace** [comment]
Hi @derrickrc. We are using [react-native-device-info](https://github.com/react-native-device-info)'s uniqueId for the `serial number` value.

The change we pushed is calling a sync function on app launch. According to [Notes](https://github.com/react-native-device-info/react-native-device-info#notes-12) here the only reason it would end up random is because IDFV doesn't exist. According to [Apple Documentation](https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor) IDFV can only be missing if the user just restarted the device and then it should be back right away.

I tried relaunching the app and restarting my iPad (iPad Pro 11") but the `serial number` stayed consistent on my side, and it is different from the `serial number` on my iPhone 14 Pro. 

I will create a new internal ticket for that but so far we cannot replicate the issue.

**Comment by derrickrc** [comment]
@heltisace thanks Eugene, let me double check this again with the merchant and get back to you.

**Comment by derrickrc** [comment]
@heltisace upon checking with a couple merchants, this does appear to be resolved - thank you. I will close for now and in case it regresses, I will reopen.

**Comment by derrickrc** [comment]
@heltisace thanks! As an FYI, in the end we factory reset the iPad and set it up as new, and the deviceSerialNumbers were different.

**Comment by derrickrc** [comment]
@moritzh it was the latest version in the Apple App Store as of Dec 21, 2022. Thanks!

**Comment by MAlliShopify** [comment]
Hi Team,
I ran some test for the serial number issue, please see attached logs for details.
Test 1: Fresh install of 8.2.0
Test 2: Delete the App then fresh install of 8.2.0
Test 3: Device Reset (Erased the device) Installed 8.2.0
Thank you

## Logs
[Fresh Install 8.2.0.zip](https://github.com/Shopify/shopify-app-bridge/files/10677553/Fresh.Install.8.2.0.zip)
[Delete App and Install 8.2.0.zip](https://github.com/Shopify/shopify-app-bridge/files/10677554/Delete.App.and.Install.8.2.0.zip)
[Device Reset and Install 8.2.0.zip](https://github.com/Shopify/shopify-app-bridge/files/10677557/Device.Reset.and.Install.8.2.0.zip)
