### ISSUE TITLE
AppBridge.Actions.AppLink for single page apps

### ISSUE THREAD

**Issue by jesper-madsen** [Shopify/shopify-app-bridge#144]
Firstly thanks for making and maintaining App Bridge 🥇 

### Describe the feature you’d like

Currently AppLink / NavigationMenu requires a `destination` parameter to be an URI.

```
const itemsLink = AppLink.create(shopifyapp, {
   label: 'Items',
   destination: '/test', // <- this is required
});
```

The issue is that for single page applications this cause the iframe to reload.
Instead it would be more performant to just subscribe to clicks on the menu items, and do the redirect in the app it self.

### Describe alternatives you've considered

Perhaps I'm missing something here, and I just misunderstood the documentation. But it would be cool to have the `destination` be an optional parameter, and when not set, no redirect would be done by app bridge.

I've tried adding diffrent destinations like `/` and `/?test=1` but they all cause a redirect.

I was not able to prevent this behaviour from happening.

**Comment by jagthedrummer** [comment]
I'm having the same problem. Using the side links provided by NavigationMenu/AppLink means that there's always a flash of the splash page as users navigate between portions of the app. This doesn't happen if I use tabs at the top of each app screen (which is now recommended against by Shopify).

Based on how to handle events with a `Button` in the title bar I'd expect to be able to do something like this:

```javascript
  const settingsLink = AppLink.create(app, {
    label: 'Settings',
    // Ideally I wouldn't need to supply destination since I'd be handling the destination
    destination: '/settings', 
  });
  
  settingsLink.subscribe(AppLink.Action.CLICK, data => {
    Turbo.visit('/settings');
  });
```

Alternatively, and maybe even better, would be some way to tell `NavigationMenu` where/how to find a session token so that it could supply the correct header.

```javascript
  function getSessionToken(){
    // The current token is always stored here.
    return window.sessionToken;
  }

  const navigationMenu = NavigationMenu.create(app, {
    items: [itemsLink, settingsLink],
    tokenRetriever: getSessionToken
  });
```

**Comment by diemah77** [comment]
Definitely +1 for a click subscription as we are handling routing ourselves.

**Comment by ascherkus** [comment]
I can confirm that subscribing to Redirect.Action.APP on 3.4.3 works with version 9.98.1 of the Shopify Android app with optimize loading on mobile enabled.

However, the issue I'm currently facing is that after getting the event the app still performs a top-level navigation to the page instead of letting the single page app handle the navigation.

For example with the following code:
```
app.subscribe(Redirect.Action.APP, payload => {
    alert(`Navigated to ${payload.path}`);
});
```

... and then clicking on Settings from the drop-down navigation menu will result in getting the alert with the payload but then the app navigates to "/settings?embedded=1&hmac..." and the app reloads.

Is there a way to tell AppBridge to let the single-page app handle navigations?

**Comment by henrytao-me** [comment]
Updates: I found the bug when mobile optimization is enabled. I pushed a fix for this. It will be available in upcoming release, targeting March 13th 🙇
