### ISSUE TITLE
Note Attributes not recorded at Checkout in some instances

### ISSUE THREAD

**Issue by jayesbe** [Shopify/shopify-app-bridge#146]
## Describe the bug

On Shopify POS - when note attributes are applied to the Cart, after the user taps checkout, there is no guarantee the note will be saved to the Order.

This is impacting client processes. We can't recreate a missing note.  Our clients have records from Shopify Reports that shows orders are missing the note. 

Another client on the Shopify Partners slack has mentioned this occurs 5% of the time to their own clients. 

### To Reproduce

There is no direct way to reproduce.. it's random.  

Steps to reproduce the behaviour:

1. Just create a cart and add note attributes.  
2. Then tap Checkout. 

Do it enough and you should come across an order where the note attributes are not saved.  

### Expected behaviour

The note attributes should be saved for every single order no exception

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- https://unpkg.com/@shopify/app-bridge@3.2/umd/index.js

## Platform

Shopify POS
- Build Number = 1642
- iPadOS = 15.5 ( 5th gen )

Clients have mixed versions iOS versions however all running the latest Shopify POS.

### Additional context

Our code applies note attributes programmatically and closes our third party app window. We ensure the notes are applied before we even close the window.  We asked our clients to always ensure the notes are visibile on the Cart before they tap Checkout.  They have all confirmed this is the case and still have Shopify Reports showing Orders missing the note.

**Comment by vctrchu** [comment]
> Hey team, sorry for the wait!
> This is the video recording they sent us: 
> 
> https://user-images.githubusercontent.com/29528613/194120393-2560d8fb-41a3-4835-96be-aad176b5318a.mp4
> 
> Just this one app: "Dennis Custom Actions" - client_id = 6972315

**Comment by vctrchu** [comment]
The issue has been noted and the team will begin taking a look. Thank you for surfacing this with us.

**Comment by coderBackPacker** [comment]
@jayesbe 
We have not been able to reproduce the issue despite placing as many as 50 orders. In each case, I was able to see the order noteAttributes upon order completion. 
Please let us know if there are specific steps where you could see this happening. 
Do you also have an example of a client order where this happened. We can try to track down the order and investigate if there was anything out of normal

**Comment by jayesbe** [comment]
@coderBackPacker I need to reopen this ticket.

I just got contacted again today by a client and also have an example from a few days ago from another.  This is wide spread.

From my Client

```
 We have been having issues with orders from the POS not deducting the store credit used from the customer's account.

I just found out about this today, and this is very difficult for us to audit, but thus far I have found at least 4 orders where the Rewardify app was used at the POS to apply store credit to the order, but the store credit was never deducted from the customer's account.

Now I need to review all of my orders to see if there are any additional examples of this happening, and manually correct/fix those accounts/orders.

The orders in question are 40458, 40109, 40141, and 39631.

This is especially troubling because unless a customer tries to use their store credit again relatively quickly and with the same cashier we have no really easy way to know the store credit wasn't deducted from the customer's account unless we start manually checking every order after it processes which would be a huge time sink.

Please Help!
```

The client here is http://halcyon-games.myshopify.com/

Those orders that are being referenced are 

39631 -> 5153643659547
40109 -> 5200925917467
40141 -> 5200966648091
40458 -> 5204178436379

The reference is the Shopify ID for each order provided. 

I will get back to you with additional information from the other client that is also complaining of this issue.

**Comment by jayesbe** [comment]
@coderBackPacker  please reopen this issue.

**Comment by bwright42tx** [comment]
I am the client listed above, http://halcyon-games.myshopify.com/

We hsve identified about 10 more orders affected with another 300 plus orders we need to manually review just to finish auditing November, and given that we had an order affected on November 1st I have no idea how far back into October we will need to review.  This has already resulted in hundreds of dollars if discounts that should not have been applied (because the rewardify account is not being updated to reflect the spent credit, because the note is not being applied to the order), as I finish auditing these november orders (a very time consuming proccess beca use I

**Comment by jayesbe** [comment]
@coderBackPacker 

You are really confusing yourself with the credit aspect. Please disregard this entirely - it has nothing to do with your system.  The issue is the fact that the note attributes are not being recorded correctly at checkout. Please understand this issue. This is the issue.  Our system is expecting that note attribute.

If you need an explanation - it's this.   A discount code may be worth $10 .. but only $1 of that discount may be related to store credit.  If a discount of $10 is applied - how would Rewardify know only $1 of that $10 discount is store credit?  We don't - unless that note attribute is recorded correctly.

So again.. please understand the entire issue right now is the note attributes not being recorded correctly.  That's it.

**Comment by bwright42tx** [comment]
@coderBackPacker 

I am not the developer, just a customer of both Rewardfy and Shopify who is experiencing this problem and needs it solved now, not tomorrow, not three weeks from now, today.  My store manager is now spending his time today fixing customer account balances in Rewardify due to discrepancies caused by the issue.  Just from September 1st there is over $5000 of credits that were not removed from rewardify.  I keep mentioning that, but that's not the shopify issue, that's the affect the shopify issue is having on rewardify.

I don't know how the APIs work with shopify between the apps like rewardify and the Shopify POS app, but what I do know is once the order is created (which my understanding is after the checkout process is complete), Rewardofy then looks at the order and performs a few actions, one of those actions is looking for the note, and if it finds the note, it then knows that it did to deduct store credit from the customer's account and proceeds to do that.  The order creation is what triggers Rewardofy to look at the order, the note is what tells it what to do.

For us, the Rewardify App on the POS is just doing two simple things, showing us how much store credit a customer has available, and allowing us to apply it to the order.  My understanding is at the same time the Rewardfy App adds the discount to the order it also creates the note on the order.  

For example, a customer comes in and orders a $100 item.  We bring the item up in the POS, add the customer to the order, then click the rewardify tile to access rewardify, it shows the customer has $125 in store credit, but the customer is saving some of that for a rainy day and only wants to use $50.00 on this order, so we tell Rewardfy to apply $50 to this order.  Rewardify then adds a discount to the order titled Store Credit for $50 and a Note to the order "Rewardify Store Credit Amount: 50.00"

We then give the customer his new total and complete the transaction/checkout.  After that is completed, completely separate from any POS actions, the new order generated in Shopify triggers the Rewardify app to process the order (granting rewards, checking for that order note, etc.)

Something is happening between when the discount is added to the cart by rewardify and the checkout process completes that is removing the note from the order.  That is the problem!!!!!!  And it s only happening on a small percentage of orders as I detailed above, but it is definitely happening on enough to cause significant problems. I don't see how it can be the rewardify app doing that because at that point rewardify is done interacting with the cart it added the discount and the note to the cart, then sent us back to the Shopify POS to finish processing the order.

**Comment by bwright42tx** [comment]
@coderBackPacker @jayesbe 

I'm not sure if additional data is helpful or not, but yesterday we had 47 total orders, 10 of those involved a store credit discount using Rewardify.  6 of those were missing the note, 4 had the note, timing was interspersed throughout the day with good and bad orders intermixed.

Today thus far we have done only 9 orders so far, 5 of those have involved a store credit discount using Rewardify, and all 5 of those have properly had the note attached to the order.

**Comment by coderBackPacker** [comment]
@bwright42tx 
Wanted to confirm the steps you do at the store so I attached a video below. 
I added customer and line item to the cart then did the steps show in the video
https://user-images.githubusercontent.com/69323793/203576588-b9d6fa78-050c-424b-8c68-9616d291a02e.mp4

**Comment by bwright42tx** [comment]
@coderBackPacker Yes, that video shows the process.  Sometimes the store credit does not cover 100% of the order and you have to complete the checkout with payment via Cash, Credit Card, etc.

**Comment by bwright42tx** [comment]
Just had another order with the issue.  #40741

**Comment by coderBackPacker** [comment]
@bwright42tx 
We have been investigating the mentioned bug and we will have some results reported soon. 
Meanwhile, we propose one solution that should reduce the repetition of the issue. 
Can you please inform the staff to always wait for 2-3 seconds and ensure that both `the discount` as well as `the note attributes` show on the cart before clicking the `Checkout` button 

thank you

**Comment by bwright42tx** [comment]
@coderBackPacker thanks for the update.  I will let my staff know of the work around.  Thanks for working to get to the bottom of it.

**Comment by coderBackPacker** [comment]
@jayesbe 
After investigating the issue, we have determined that the cause of the missing note attributes is due to `closePOS` being executed before the `setDiscount` and `updateProps` are complete. Both of these are `async` functions, and therefore developers should ensure they are complete before closing their application on POS. We suggest either passing a callback, or using async-await.

For merchants affected, they can mitigate by waiting a few seconds after closing the Rewardify app to give the app time to complete async calls. This should ensure that all metadata is synced before executing a Checkout.
We will investigate the addition of checks to our `app-bridge-sdk` to protect against the third-party applications closing before all their functions have been processed.

**Comment by jayesbe** [comment]
@coderBackPacker 

Please review the code I posted above. It literally shows that I am passing a callback and all that callback does it create a notice and close POS. It is however passed as a callback which occurs after the discount has been applied and after the note has been applied. 

The flow from the code above is obvious. 

1. Apply discount 
2. Apply note
3. After note is applied,  show notice and closePOS

Please review the code above and tell me where the mistake is..

**Comment by coderBackPacker** [comment]
@jayesbe Please find a proposed solution. This example is only for explanation purposes:
```tsx
if (res.privileged.privilegedOrderDiscount > 0) {
    await RwCart.setDiscount({
        amount: Number(res.privileged.privilegedOrderDiscount),
        discountDescription: "Privileged Order Discount",
        type: 'flat'
    });

    await RwCart.updateProps({
        'Rewardify Privileged Order Discount': String(res.privileged.privilegedOrderDiscount)
    });

    applied = true;
}
// END ORDER DISCOUNT

if (applied) {
    Rewardify.toastNotice('Discounts Applied.');
}
else {
    Rewardify.toastNotice('No Discounts Available.');
}
Rewardify.closePOS();
```

**Comment by jayesbe** [comment]
@coderBackPacker 

There is a reason we are using callbacks and that's because we are using vanilla js with no async await. It's all callbacks. 

Please provide an example that uses callbacks.

**Comment by jayesbe** [comment]
@coderBackPacker @bwright42tx 

I have added a timeout of 1 second into our logic. 

```
                                                RwCart.setDiscount({
                                                    amount: Number(discountAmount),
                                                    discountDescription: discDesc,
                                                    type: 'flat'
                                                }, function() {
                                                    RwCart.updateProps({
                                                        'Rewardify Store Credit Amount': String(res['rewardify-discount'])
                                                    }, function() {
                                                    	Rewardify.toastNotice('Credit Applied.');
                                                    	setTimeout(function() {
                                                    		Rewardify.closePOS();                                                        	
                                                        }, 1000);
                                                    });
                                                }); 
```

it's a "hacky" solution since it's not perfect and it assumes 1 second will be enough time to hold back to ensure the discount will be applied.  Hopefully regardless it will cut down most orders that are not recorded correctly.

We simply wait to close the third party window by 1 second.

**Comment by vctrchu** [comment]
Hi @jayesbe A fix for this issue has been merged. You should see your app work without this hack on the next app update. If you see longer delays than usual before the web view closes, it may be a combination of our fix and your 1 second delay. Thanks.

**Comment by henrytao-me** [comment]
@jayesbe, below is from what you said above 

> What I asked our clients to do was check to ensure that note was always added - this they confirm is the case. The note shows up as they expect, however, when they tap checkout.. randomly, the note may not be recorded.

=> This means that the property actually shows up in the Cart UI after the embedded app is closed. However, the property is not recorded after checkout flow is finished. Is it correct?

**Comment by jayesbe** [comment]
@vctrchu great to hear thanks. I'll remove the delay when the update is released.. can you mention which release this is related to? is it the shopify-app-bridge or the iOS app itself ?

> => This means that the property actually shows up in the Cart UI after the embedded app is closed. However, the property is not recorded after checkout flow is finished. Is it correct?

Yes correct. The UI always showed the property after the embedded app closed.  It was only after the customer tapped Checkout that it may or may not be recorded. Clients were told to wait a second before tapping the Checkout button. 

The delay I added forces the user to wait by delaying the closing of the embedded app screen by one second.

**Comment by 71m024** [comment]
I think too, that you should reopen this issue @coderBackPacker  

We have 400 to 800 Orders per day and on some days, we have 2-4 Orders with missing cart-attributes.  
I set the the attributes with native html input-elements and made shure, that they are submitted correctly.  

From my perspective this must be a problem on the server side because there is no JavaScript involved and it is pretty obvious, that the submitted cart-form  sends the attributes. I can't imagine, that some browsers simly don't submit some html input-elements.  

There is also a discussion about this here: https://community.shopify.com/c/shopify-discussions/order-management-note-attributes-is-empty-sometime/m-p/1900348#M334784  

And a workaround here: https://community.shopify.com/c/shopify-discussions/attribute-data-recently-stopped-coming-through-on-orders/td-p/2105835  
I modified this to native javascript and am currently testing it with these functions:  

```javascript  
function initCartAttributePosters() {
    registerAttributePoster('date-from-input', 'date-from');
    registerAttributePoster('date-to-input', 'date-to');
    registerAttributePoster('customer-locale-input', 'customer-locale');
}

function registerAttributePoster(elementId, attributeName) {
    let inputElement = document.getElementById(elementId);
    if (inputElement) {
        let postAttribute = (value) => {
            fetch('/cart/update.js', {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                },
                body: JSON.stringify({
                    attributes: {
                        [attributeName]: value
                    }
                })
            });
        }
        postAttribute(inputElement.value);
        document.getElementById(elementId)?.addEventListener('change', (event) => {
            postAttribute(event.target.value)
        });
    }
}
```

**Comment by 71m024** [comment]
I can confirm that this workaround works for us but should definitely not be necessary from my perspective.
