### ISSUE TITLE
Where is https://github.com/Shopify/app-bridge?

### ISSUE THREAD

**Issue by assaflei** [Shopify/shopify-app-bridge#18]
Sorry if the question isn't related to this location...

This is a general question regarding the location of the repository containing the components: app-bridge-react and app-bridge-utils

The npm package pages of these components reference this url which throws 404 error: https://github.com/Shopify/app-bridge
Can you provide the current repository location?

Thanks

**Comment by iainmcampbell** [comment]
Hi Assaf, the code for App Bridge is in a private repo (https://github.com/Shopify/app-bridge) which is not publicly accessible. That’s why you’re getting a 404.

You can find documentation for `app-bridge-react` on shopify.dev: https://shopify.dev/tools/app-bridge/react-components.

You can find documentation for `app-bridge-utils` on shopify.dev as well (although not as clearly labelled):
- https://shopify.dev/tools/app-bridge/actions/modal#set-modal-size
- https://shopify.dev/tutorials/authenticate-your-app-using-session-tokens

**Comment by antwal** [comment]
Hi @iainmcampbell , how can I access the code repo to update my old custom version? Thank you.

**Comment by antwal** [comment]
Hi @martinsileno, They did not answer me, it seems that for them there is not much interest in the developer community anymore, but they are building a closed system only with the technologies they use, with little compatibility with other frameworks. In the end I just had to give up and switch to another unofficial framework, because ReactJS for my use is extremely inconvenient to use
