### ISSUE TITLE
Include Product Title in ResourcePicker when type is ProductVariant

### ISSUE THREAD

**Issue by Praveen2106** [Shopify/shopify-app-bridge#245]
### Describe the feature you’d like
Include Product Title in the results when the Resource Picker Type is selected as 'ProductVariant'. Without the Product Title, the ProductVariant resource picker is almost useless. 

![image](https://github.com/Shopify/shopify-app-bridge/assets/8241455/e05ac9ee-9169-4c5e-92fc-88cad9d58f31)

It is extremely difficult, if not impossible, for the merchants to select the correct variants.

**Comment by Praveen2106** [comment]
This already works as expected within the Shopify Admin. 

![image](https://github.com/Shopify/shopify-app-bridge/assets/8241455/1077199d-8bf6-406f-a876-dc56087f9cd0)

However, the app bridge ResourcePicker does not display the Product Titles. 
![image](https://github.com/Shopify/shopify-app-bridge/assets/8241455/b92b0149-819b-4370-959c-3e7a67e27bcf)

**Comment by Praveen2106** [comment]
Any updates on this?

**Comment by capatina** [comment]
Hello any update on this? Making it impossible to use new app bridge

**Comment by joefitter** [comment]
+1 on this. I am currently unable to use the resource picker due to this issue. I need to select from a subset of variants, and the product type resource picker doesn't allow filtering child variants.

The variant type picker is currently unusable due to no product/image/info being displayed. Attached an image from a recently set up development store - no data is shown at all for products with only a single variant.

Would be **fantastic** if this issue could be addressed :)

<img width="628" alt="Screenshot 2024-07-14 at 13 57 09" src="https://github.com/user-attachments/assets/2aadbc43-2de5-44ac-86c9-113a435846a4">

**Comment by Praveen2106** [comment]
Is there any progress on this feature? Looking forward to making it easier for merchants to pick the variants with the Resource Picker. The current version with resource type 'Variant' makes no sense.

**Comment by boronine** [comment]
Still broken 11 months later..

![Image](https://github.com/user-attachments/assets/4b6bc633-56a6-4d95-8cf2-e88ab6cd1570)

**Comment by capatina** [comment]
Hello, this is blocking us from using new app bridge. Can you please provide an update?

**Comment by boronine** [comment]
We could not get `type: "variant"` to work, but this works for us:

```javascript
shopify.resourcePicker({
  type: "product",
  action: "add",
  multiple: true,
  filter: {variants: true},
})
```
