### ISSUE TITLE
Resource Picker Issue with latest app bridge version

### ISSUE THREAD

**Issue by RobinShineDezign** [Shopify/shopify-app-bridge#268]
## Describe the bug

When using the Resource Picker with the "Product" resource a **total_variants** field is needed to determine whether all variants have been selected or a subset. Currently there is no way to find this out from the resource picker response, other than by making an additional request after making a selection.

![image](https://github.com/Shopify/shopify-app-bridge/assets/113879222/1a56de64-6c03-4337-8148-3d620fa8d67f)

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

**We are using latest version:** 

<head>
  <meta name="shopify-api-key" content="%SHOPIFY_API_KEY%" />
  <script src="https://cdn.shopify.com/shopifycloud/app-bridge.js"></script>
</head>

**Comment by ryanrphillips** [comment]
There is already an open issue asking for this value to be added to the resource picker response: https://github.com/Shopify/shopify-app-bridge/issues/235

**Comment by meandillar** [comment]
> I think the long term approach for ResourcePicker is that it should return just selected ids. Apps need to perform extra graphql call to get what they need because each app wants different information.

It would be nice to have the ability to specify the return fields rather than making an extra request.

**Comment by meandillar** [comment]
@henrytao-me After further testing it is apparent that the solution provided by @Stef733 will only work if all option combinations are valid variants.

For example, I have a product with 7 Flavours & 2 Sizes. Using the reduce method brings the total number of possible variants to 14 (7 * 2).

The problem arises when some of the flavours are only available in one size rather than both. In my case I only have a total number of 10 variants available because 7 flavours are available at 1kg, but only 4 flavours are available at 1.5kg, meaning that to get the correct number of variants I still need to perform an extra request.

**Comment by henrytao-me** [comment]
I see. 

> It would be nice to have the ability to specify the return fields rather than making an extra request.

I will cycle back to the team.

**Comment by meandillar** [comment]
@henrytao-me hey any chance we could have this issue reopened?

**Comment by meandillar** [comment]
@henrytao-me Much appreciated, that works great!
