### ISSUE TITLE
useNavigate hook is missing in the new version

### ISSUE THREAD

**Issue by s-tyshchenko** [Shopify/shopify-app-bridge#294]
## Describe the bug

Seems like useNavigate is no longer present in the [@shopify/app-bridge-react@v4](https://www.npmjs.com/package/@shopify/app-bridge-react), however it's still present in the [documentation](https://shopify.dev/docs/api/app-bridge/previous-versions/actions/navigation/redirect-navigate#example-code) 

Error:
`Module '@shopify/app-bridge-react' has no exported member useNavigate`

### To Reproduce

Steps to reproduce the behaviour:

1. import {useNavigate} from '@shopify/app-bridge-react';

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- `@shopify/app-bridge` @ `^3.7.10`
- `@shopify/app-bridge-react` @ `^4.0.0`
- `@shopify/polaris` @ `^12.0.0`

## Platform

- OS: MacOS
- OS Version: [for example 10.15.5]
- App: Shopify Remix

**Comment by mesija** [comment]
It's strange that there is no answer here, but it looks like this can be easily circumvented since the new version can work correctly with the open function, so you can replace the code
`const navigate = useNavigate();
navigate('/test')`
with
`open('/test')`

More information is available here, on the JavaScript tab in the code samples https://shopify.dev/docs/api/app-bridge-library/apis/navigation
