### ISSUE TITLE
Invalid Host Origin

### ISSUE THREAD

**Issue by nikunj-crawlapps** [Shopify/shopify-app-bridge#296]
## Describe the bug

Getting `Invalid Host Origin` when trying to access sub-domain.

### Expected behaviour

I am trying to release my new updated app as beta release so merchant can use both app based on the preference.

I have two setup of projects for both based on the preference. merchant able to switch over to app.

Setup Details:

Existing App: https://main-domain.com
New App (Beta): https://v2.main-domain.com

## Contextual information

A new version of the app has been developed and set up on a subdomain (https://v2.main-domain.com/) to ensure a smooth transition for users. However, the "Invalid Host Origin" error is impeding the use of the new app with the subdomain.

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- "@shopify/app-bridge": "^3.7.9"
- "@shopify/app-bridge-react": "^3.7.9"
- "@shopify/polaris": "^11.1.3"

**Comment by nikunj-crawlapps** [comment]
@jzazove I updated my app bridge version but issue remains same.

**Comment by jzazove** [comment]
And what values show when you use `shopify.config.appOrigins` ?

**Comment by jzazove** [comment]
I would recommend these guides for authentication:
[Shopify managed installation](https://shopify.dev/docs/apps/auth/installation)
[Token exchange getting started](https://shopify.dev/docs/apps/auth/get-access-tokens/token-exchange/getting-started)

**Comment by henrytao-me** [comment]
> A new version of the app has been developed and set up on a subdomain (https://v2.main-domain.com/) to ensure a smooth transition for users. However, the "Invalid Host Origin" error is impeding the use of the new app with the subdomain.

I am not really sure what your flow here. May I have your current appId and new appId?

- In general, if your app sets application url as https://main-domain.com/, you cannot redirect within the app iframe to different domain / subdomain like https://v2.main-domain.com/ => the postMessage won't work due to origin check. 
- If you want to redirect to different app within your app, you need to use Remote Redirect (in `@shopify/app-bridge`) or Navigation API in latest App Bridge https://shopify.dev/docs/api/app-bridge-library/apis/navigation
- This comment about appOrigin https://github.com/Shopify/shopify-app-bridge/issues/296#issuecomment-1981526318 refers to the ability to call `fetch` that includes `bearer token` to allowed list that you specify. By default, only fetch request to your application url contains `bearer token`.

**Comment by nikunj-crawlapps** [comment]
@henrytao-me @jzazove 
Is it not possible through the single app?
I am using same app for both setup. based on the customer preference I wanna load specific domain which servers different version of app.

**Comment by henrytao-me** [comment]
> Is it not possible through the single app?

Correct. It is not possible. You need to use different paths for different app UI instead of different subdomain unfortunately.

**Comment by nikunj-crawlapps** [comment]
@henrytao-me Thank you for guide me. I have some query can please guide me on this as well.

Is there any other approach to release beta for merchants?

Are we need to verify the new app if we follow two app approach? 
Can we provide our new version app without verifying from the Shopify?  as of our old app already verified and on Shopify store.
