### ISSUE TITLE
Restore FullScreen Functionality in AppBridge V4

### ISSUE THREAD

**Issue by mirceapiturca** [Shopify/shopify-app-bridge#303]
The FullScreen API was deprecated in favor of a Modal-based approach. This change presents significant drawbacks for application vendors, as outlined below:

**Reduced Interface Space**: The FullScreen API was previously leveraged due to its capability to support complex user interfaces that necessitate expanded visual real estate. The transition to Modal constrains this space, negatively impacting user experience and functionality.

**Integration Issues with Polaris Components**: Components from the Polaris design system, such as Popover and Tooltip, don't work within a Modal context. This compatibility issue undermines the consistency and reliability of user interfaces built using these components.

**User Interface Disruptions**: The nested nature of modals and other overlays within the Modal framework leads to a cluttered and confusing user interface. This design choice detracts from the overall user experience, making navigation and interaction less intuitive.

**Complexities with Embedding iFrames**: The Modal implementation introduces complexities when embedding iFrames, given that the modal itself functions as an iFrame. This layering complicates integration and limits the functionality of embedded content within the modal environment.

The FullScreen API offered a straightforward, efficient solution for achieving better user interfaces. Its removal in favor of a less versatile and more problematic Modal approach raises questions about the rationale behind this decision.

**Comment by jzazove** [comment]
The unfortunate part is that some apps were abusing Fullscreen leaving merchants lost.  Some apps, for example, were not even implementing the Polaris Top Bar.  We will look to adding more features to the max modal in the latest version of App Bridge.

**Comment by alexdover** [comment]
It is a real shame that the actions of the apps abusing have ended up spoiling the experience merchants get with apps doing the right thing.

From our point of view, it has really hurt our UI. We were really proud of our fullscreen editor and merchants loved it.

Would you consider allowing it for Built for Shopify apps?

**Comment by chindnguyen** [comment]
The max modal is working so badly, don't know why you guys can release and force us to use it while still having many issues.
We can do nothing with our app page builder, the styled-components cannot work, popover, overlay cannot work too.
The Title Bar with grouped secondary buttons cannot work, it only shows the secondary button, the button with the variant breadcrumb cannot work too 👎 

You guys forced us to use max modal of the new app-bridge instead of the old fullscreen mode, but the app Shopify such as Emails or Translate & Adapt still using the old Fullscreen mode, which is so bad to app partners
