### ISSUE TITLE
Polaris <Tooltip> component does not work in modal

### ISSUE THREAD

**Issue by noelgoodday** [Shopify/shopify-app-bridge#376]
## Describe the bug

Tooltips don't display when used in a component that's rendered within the AppBridge modal.

This might be related to https://github.com/Shopify/shopify-app-bridge/issues/316 as it's yet another Polaris component that doesn't work with this modal.

**Comment by Zetxus** [comment]
ColorPickers are the same. Pretty much anything that requires some form of an extra element to show up over the current content will instead be below the Modal. 

And just to throw this in in case someone suggests it - yes, using a Modal with an `src` attribute does fix this. However due to it being limited as mentioned in this comment and the few below it https://github.com/Shopify/shopify-app-bridge/issues/364#issuecomment-2144431103 it does not serve as a reliable fix for any complicated solutions.

**Comment by princerafid01** [comment]
Same problem. Any solutions? Anyone here? It's annoying.

**Comment by MitchLillie** [comment]
Hi, this should be fixed as of the latest Polaris version (13.9.0) ([changelog](https://github.com/Shopify/polaris/releases/tag/%40shopify%2Fpolaris%4013.9.0)).

Can you please update to that version and see if you're still seeing the issue?

**Comment by shino022** [comment]
> You must be using Polaris 13.19.x or higher for the Polaris App Provider to contextualize components built with React Portals.
> 
> https://shopify.dev/docs/api/app-bridge/using-modals-in-your-app#react-components-using-react-portals

How can i install `13.19.x` version?? The latest version I can find is `13.9.5`
