### ISSUE TITLE
APP::ERROR::INVALID_CONFIG: shopOrigin must be provided issue on Safari

### ISSUE THREAD

**Issue by GherghelAndrei** [Shopify/shopify-app-bridge#4]
## Describe the bug
I'm using koa-shopify-auth, and I'm setting a cookie with shopOrigin. On the frontend i try to get that shopOrigin from cookie to configure App Bridge. On Chrome/Firefox it works, on Safari i get "APP::ERROR::INVALID_CONFIG: shopOrigin must be provided". I've tried to get the shopOrigin from the Embedded url that contains hmac state and shop, when my app is in iframe, but i can't, trying to auth the app I have the same error.

### To Reproduce

Steps to reproduce the behaviour:

1. Create an app with koa-shopify-auth, set a cookie with shopOrigin
2. Wrap the react app in App Bridge Provider
3. Try to auth your app in Safari

<img width="1048" alt="Screen Shot 2020-08-07 at 7 01 10 PM" src="https://user-images.githubusercontent.com/18439989/89686379-f3b55580-d906-11ea-98e2-e0ea2b441dc0.png">

<img width="678" alt="Screen Shot 2020-08-07 at 7 06 09 PM" src="https://user-images.githubusercontent.com/18439989/89686395-f7e17300-d906-11ea-8996-12c79fe824f7.png">
<img width="412" alt="Screen Shot 2020-08-07 at 7 07 38 PM" src="https://user-images.githubusercontent.com/18439989/89686405-f9ab3680-d906-11ea-9392-2a7fe5b5fb73.png">

### Expected behaviour

With window.name I'm checking to see If the app is in the iframe.  It should display loading until the app is in iframe.

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- `@shopify/app-bridge-react` @ `^1.26.2`
- `@shopify/polaris` @ `5.1.0`

## Platform

- OS:  macOS
- OS Version: Mojave 10.14
- App: Safari

### Additional context
backend with koa
frontend with react, serving react from koa as seen in the screenshot (static_pages)

**Comment by GherghelAndrei** [comment]
After some console.logs I've seen that on Safari I can't set cookies, but on chrome it works. My cookies are enabled in Safari...

**Comment by iainmcampbell** [comment]
Hi Andrei!

Safari aggressively blocks third-party cookies with the [Intelligent Tracking Protection (ITP) system](https://webkit.org/blog/7675/intelligent-tracking-prevention/). ITP has been [getting stronger with each new release of Safari](https://webkit.org/blog/category/privacy/). Embedded apps in Shopify are affected by ITP, as you experienced, because they use third-party cookies to authenticate. We were able to [work around it in the past](https://shopify.dev/tutorials/update-your-app-to-support-intelligent-tracking-prevention), but the more recent versions of ITP are too stringent.

We’ve built a [new way to authenticate embedded apps](https://shopify.dev/tools/app-bridge/authentication), using session tokens instead of cookies, which is not affected by ITP. It’s currently in beta. If Safari support is important to you, I'd encourage you to try out the new method. If you have questions about session token auth, please post in [this Shopify developer forum thread](https://community.shopify.com/c/Shopify-APIs-SDKs/Introducing-cookieless-authentication-beta-with-App-Bridge/m-p/824484).

I’m going to close this issue, as it’s not an App Bridge bug.
